### ISSUE TITLE
Initial front-end project setup

### ISSUE THREAD

**Issue by yurihnrq** [yurihnrq/next-blog-front-end#1]
## Description

Create and configure the front-end project.

## Tasks

- [x] Create Next.js App with experimental app folder
- [x] Tailwind CSS
- [x] Jest with SWC
- [x] Storybook
- [x] Eslint, Prettier and editorconfig
- [ ] Pre commit hook for linting
- [ ] VSCode debugger setup
